### ISSUE TITLE
Now available on QSC's linux repo

### ISSUE THREAD

**Issue by Senorsen** [QSCTech/zjunet#52]
HERE:

http://dl.zjuqsc.com/linux/

(deb and rpm)

Usage:
    
    wget -qO - https://dl.zjuqsc.com/linux/qsc.public.key | sudo apt-key add -
    sudo wget https://dl.zjuqsc.com/linux/debian/qsc.list -O /etc/apt/sources.list.d/qsc.list
    sudo apt-get update
    sudo apt-get install zjunet
    
...

see README.md for detailed info

**Comment by zenozeng** [comment]
:+1:
