### ISSUE TITLE
发布 1.0?

### ISSUE THREAD

**Issue by zenozeng** [QSCTech/zjunet#55]
And follow this? 

http://semver.org/lang/zh-CN/

**Comment by zenozeng** [comment]
@Senorsen ，以及不要用 v0.2.5-2 这样的 version 吧，这个是 debian 习惯的 build version，但是我们的场景下还是直接改小版本号吧。

**Comment by Senorsen** [comment]
那么我们之后就不使用release版本号，直接用version咯？
-- 噢噢，好的嘛

**Comment by zenozeng** [comment]
我觉得软件版本号和pkg 的 version 是不一样的。
一个是开发者的。一个是打包者的。
只是我们刚好两个人一样了。
我觉得开发版本号应该遵守开发版本号的习惯。
打包版本号应该遵守打包版本号的习惯。

**Comment by zenozeng** [comment]
比如原先我们打包错了，那重新打包就后面加 -2 -3 之类的。如果改了代码，对我们来说，应该改 version.

**Comment by Senorsen** [comment]
我想等到它有断线重连（比如利用if-down.d，等等）的时候再发1.0？
