### ISSUE TITLE
fish下不能运行

### ISSUE THREAD

**Issue by Zardinality** [QSCTech/zjunet#57]
bash跟zsh都正常，切到fish下就报错：
Failed to execute process '/usr/bin/zjunet'. Reason:
exec: Exec format error
The file '/usr/bin/zjunet' is marked as an executable but could not be run by the operating system.

fish version 2.2.0-827-gb064da8
发行版是LM17.3肉桂

**Comment by Senorsen** [comment]
谢谢反馈，反馈的问题疑似与 shebang line 的缺失有关：

https://github.com/QSCTech/zjunet/blob/f83f10238466d2e1735c4b3009d9dcf88fcc98fc/build/debian/build.sh#L6

**Comment by Zardinality** [comment]
多谢，fish下已经正常了
