### ISSUE TITLE
不考虑加个使用说明？

### ISSUE THREAD

**Issue by hujichn** [QSCTech/zjunet#59]
1. 首先添加账户
```
zjunet user add
```
会提示输入用户名和密码

2. 其次配置好路由
```
zjunet route
```
3. 最后进行连接
```
zjunet vpn -c
```
连接好后ping一个外网网址就可以测试是否连接成功了

我一开始没有配置路由好像就一直连不上...

**Comment by qiang92** [comment]
那大兄弟你是怎么知道怎么配路由的？man zjunet？

**Comment by hujichn** [comment]
。。。早不记得了。。

**Comment by Dawn-LX** [comment]
搞了好久，原来还有这个命令，应该加到readme里比较好吧。另外，这个是不用root权限的吧？
