### ISSUE TITLE
Fail to bring up ppp, timeout.

### ISSUE THREAD

**Issue by hgr215** [QSCTech/zjunet#64]
zjunet vpn -c
[INFO] Try to start xl2tpd if not
[INFO] xl2tpd ready.
[INFO] try disconnecting zju-l2tp-21730057
[INFO] xl2tpd-control done
01 Session 'zju-l2tp-21730057' not up
[INFO] Setting up ip route.
default via 192.168.43.1 dev wlx30b49e727226 
default via 192.168.43.1 dev wlx30b49e727226  proto static  metric 600 
169.254.0.0/16 dev wlx30b49e727226  scope link  metric 1000 
192.168.43.0/24 dev wlx30b49e727226  proto kernel  scope link  src 192.168.43.129  metric 600 
[INFO] Stopping xl2tpd
[INFO] Starting xl2tpd
[INFO] xl2tpd ready.
[INFO] Login using 21730057
**Fail to bring up ppp, timeout.**
[INFO] try disconnecting zju-l2tp-21730057
[INFO] xl2tpd-control done
01 Session 'zju-l2tp-21730057' not up
[INFO] Setting up ip route.
default via 192.168.199.1 dev wlx30b49e727226 
default via 192.168.199.1 dev wlx30b49e727226  proto static  metric 600 
169.254.0.0/16 dev wlx30b49e727226  scope link  metric 1000 
192.168.199.0/24 dev wlx30b49e727226  proto kernel  scope link  src 192.168.199.140  metric 600

**Comment by Jerry280989322** [comment]
老哥，我也碰到了这个问题，想请教一下你是怎么解决的？
我的PPP版本是2.4.7，ubuntu18.04.1 LTS
