### ISSUE TITLE
Please Help!!  Fail to bring up  PPP,time out

### ISSUE THREAD

**Issue by Jerry280989322** [QSCTech/zjunet#65]
achao@achao-OptiPlex-7050:~$ zjunet vpn -c
[INFO] Try to start xl2tpd if not
[INFO] xl2tpd ready.
[INFO] try disconnecting zju-l2tp-3150105001
[INFO] xl2tpd-control done
[INFO] Setting up ip route.
default via 10.180.32.1 dev wlx70f11c1856ce 
default via 10.180.32.1 dev wlx70f11c1856ce proto dhcp metric 600 
10.180.32.0/20 dev wlx70f11c1856ce proto kernel scope link src 10.180.47.13 metric 600 
169.254.0.0/16 dev wlx70f11c1856ce scope link metric 1000 
[INFO] Stopping xl2tpd
[INFO] Starting xl2tpd
[INFO] xl2tpd ready.
[INFO] Login using 315010****
Fail to bring up ppp, timeout.
[INFO] try disconnecting zju-l2tp-315010****
[INFO] xl2tpd-control done
[INFO] Setting up ip route.
default via 10.180.32.1 dev wlx70f11c1856ce 
default via 10.180.32.1 dev wlx70f11c1856ce proto dhcp metric 600 
10.180.32.0/20 dev wlx70f11c1856ce proto kernel scope link src 10.180.47.13 metric 600 
169.254.0.0/16 dev wlx70f11c1856ce scope link metric 1000

操作系统Ubuntu18.04.1 LTS
很难受啊   向大佬们求助～～感激不尽

**Comment by hietwll** [comment]
老哥，解决了没有

**Comment by Jerry280989322** [comment]
木有啊  能解决了吗

**Comment by hietwll** [comment]
老哥们，如果是ubuntu的话，可以尝试：安装network-manager-l2tp与network-manager-l2tp-gnome。目前已经连上了。链接：http://www.cc98.org/topic/2323871/49#1

**Comment by Jerry280989322** [comment]
> 老哥们，如果是ubuntu的话，可以尝试：安装network-manager-l2tp与network-manager-l2tp-gnome。目前已经连上了。链接：http://www.cc98.org/topic/2323871/49#1

重装了系统，解决了。。   ：）
