### ISSUE TITLE
GPG error: The following signatures were invalid

### ISSUE THREAD

**Issue by WOWNICE** [QSCTech/zjunet#72]
修改sources.list内容之后（也完成了两个curl指令）跑 apt-get update命令获得以下错误：

W: GPG error: The following signatures were invalid: ...
E: The repository 'http://dl.zjuqsc.com/linux/debian stable release' is not signed.

接着apt-get install zjunet就找不到这个包。

求解。

**Comment by Esther-99** [comment]
相同的问题……求解

**Comment by LetterLi1997** [comment]
同问求解

**Comment by tespent** [comment]
这个问题应当在九月左右就解决了
是使用的签名算法不够新导致的
可以重新试试了
