### ISSUE TITLE
网址失效了

### ISSUE THREAD

**Issue by dupeipei** [QSCTech/zjunet#73]
curl https://dl.zjuqsc.com/linux/qsc.public.key | sudo tee /etc/pki/rpm-gpg/RPM-GPG-KEY-QSC-COMP66
curl https://dl.zjuqsc.com/linux/yum/qsc.repo | sudo tee /etc/yum.repos.d/qsc.repo

你好，这两个服务失效了，文件下不下来，谢谢帮助～～～

**Comment by tespent** [comment]
前些天服务器不正常，故无法下载。现在服务已恢复～

**Comment by dawnos** [comment]
貌似又挂了

**Comment by tespent** [comment]
> 貌似又挂了

修好了……
