### ISSUE TITLE
openwrt

### ISSUE THREAD

**Issue by ghost** [QSCTech/zjunet#78]
## Environment
Please complete the following information:
- **OS:** [OS name and version, e.g. Ubuntu 20.10, CentOS 8]
- **zjunet:** [output of `zjunet -v`, e.g. 0.3.3-3]
- **xl2tpd:** [output of `xl2tpd -v`, e.g. 1.3.16]
- **network type:** [wired or wireless or ...]
- other softwares or the network condition that may related to this bug

## Bug description
A clear and concise description of what the bug is and how to reproduce it.
使用openwrt 出现连不上网，有提示pkill not found
## Output

Full output of command line tools.

If applicable, add screenshots to help explain the problem.

```
[user@host ~]# zjunet XXXX
zjunet all disconnect

## Notes
[INFO] Try to start xl2tpd if not
[INFO] xl2tpd ready.
[INFO] try disconnecting zju-l2tp-3170105432
/usr/lib/zjunet/xl2tpd.sh: line 190: pkill: not found
[INFO] xl2tpd-control done
[INFO] Setting up ip route.
default via 192.168.21.29 dev wlan0

**Comment by liuluping0106** [comment]
有没有可能出一个openwrt自己多拨的教程啊？请问
